spring:
 profiles:
  active:
  - dev
---
spring: 
 profiles: dev  #开发环境
 application： 
 name： mavencloud-config-yh-dev
---
spring:
 profiles: test #测试环境
 application：  
 name： mavencloud-config-yh-test
---
#请保存为UTF-8格式